name: Push TODO.md changes

on:
  push:
    paths:
      - 'TODO.md'
  pull_request:
    paths:
      - 'TODO.md'

jobs:
  push-todo-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow write access to the repo

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure Git credentials using GitHub token
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Commit changes to TODO.md if any changes are detected
      - name: Commit changes to TODO.md
        run: |
          git add TODO.md
          git diff-index --quiet HEAD || git commit -m "Update TODO.md"

      # Step 4: Push changes to the current branch
      - name: Push changes to current branch
        run: git push origin HEAD:${{ github.ref }}

      # Step 5: Push changes to main branch
      - name: Push changes to main branch
        run: git push origin HEAD:main --force-with-lease
